version:  '2'

services:
   op5:
     build: .
     image: "${HOSTNAME}"
     env_file:
       - op5.env
     extra_hosts:
       - "test.host.com:1.1.1.1"
       - "test2.host.com:2.2.2.2"
       - "$HOSTNAME:$MY_IPADDR" 
